#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Follow the XDG standard of file organization https://wiki.archlinux.org/index.php/XDG_Base_Directory where possible
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
if [ ! -w ${XDG_RUNTIME_DIR:="/run/user/$UID"} ]; then
    echo "\$XDG_RUNTIME_DIR ($XDG_RUNTIME_DIR) not writable. Setting to /tmp." >&2
    XDG_RUNTIME_DIR=/tmp
fi
export XDG_RUNTIME_DIR

export HISTFILE="$XDG_DATA_HOME"/zsh/history

export VIMCOLORDIR="$XDG_DATA_HOME/dein/repos/github.com/jefheaton/citylights.vim/"
export VIMCOLORFILE="$XDG_DATA_HOME/dein/repos/github.com/jefheaton/citylights.vim/colors/citylights.vim"

###############
#  NVM & NPM
######

export NVM_DIR="$XDG_CONFIG_HOME/.nvm"

# npm
# see npm config ls -l | grep /
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/config
export NPM_CONFIG_CACHE=$XDG_CACHE_HOME/npm
export NPM_CONFIG_TMP=$XDG_RUNTIME_DIR/npm

# complete -C /usr/local/bin/vault vault

# taskwarrior data
export TASKRC=$XDG_CONFIG_HOME/task/.taskrc
export TASKDATA=$XDG_DATA_HOME/task

# vault
export VAULT_ADDR='https://secrets.volantio.com:8200'
