#!/usr/local/bin/zsh
# File: .zshrc
# Author: Jeff Heaton <jeff@jgheaton.com>
# Last Modified Date: 2018.12.30

# TODO set up Mutt
# TODO set mutt to disable or display links
# TODO Consolidate/forward emails to one address

###############
#  Prezto
######
# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Load NVM using manual install for XDG
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Use vi-mode in zsh https://sanctum.geek.nz/arabesque/vi-mode-in-bash/
# set -o vi? https://dougblack.io/words/zsh-vi-mode.html
bindkey -v

# Change cursor shape between insert and normal mode in iTerm2.app
# https://emily.st/2013/05/03/zsh-vi-cursor/
function zle-keymap-select zle-line-init
{
    # change cursor shape in iTerm2
    case $KEYMAP in
        vicmd)      print -n -- "\E]50;CursorShape=0\C-G";;  # block cursor
        viins|main) print -n -- "\E]50;CursorShape=1\C-G";;  # line cursor
    esac

    zle reset-prompt
    zle -R
}

function zle-line-finish
{
    print -n -- "\E]50;CursorShape=0\C-G"  # block cursor
}

zle -N zle-line-init
zle -N zle-line-finish
zle -N zle-keymap-select

# 10ms for key sequences, faster normal/insert switch
KEYTIMEOUT=1

###############
#  aliases
######
# use a bare repo to track dotfiles
# https://developer.atlassian.com/blog/2016/02/best-way-to-store-dotfiles-git-bare-repo/
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'

alias cd="cdls"
alias docs="cd ~/iA/Documents"

# colorful list view
alias ll="k -h --group-directories-first"
alias lla="ll --all"

# in columns with slashes after directory
alias ls="gls -CFG --color --group-directories-first"

# pipe long directory to less so they can be scrolled easily
alias lsl="ls -lhFA | less"
alias la="ls -a"
alias lt="tree && echo 'using 🌳 tree 🌳'"
alias man="tldr"

# create intermediate directories and tell us about it
alias mkdir="mkdir -pv"
alias top="htop"
alias tmux='TERM=xterm-256color tmux -f "$XDG_CONFIG_HOME"/tmux/tmux.conf'
alias src="source $XDG_CONFIG_HOME/zsh/.zshrc"
alias vi="nvim"
alias vimrc="vi $XDG_CONFIG_HOME/nvim/init.vim"
alias wttr="curl wttr.in"
alias zshrc="vi $XDG_CONFIG_HOME/zsh/.zshrc"

# ## Git Aliases
alias gA="git add ."
alias gaN="echo 'git add . --intent-to-add' && git add -N ."
alias gb="git branch"
alias gbr="git branch --remote"
alias gc="git clone"
alias gck="git checkout"
alias gf="git fetch"
alias gm="git merge"
alias gp="git pull"
alias gpr="git pull --rebase"
alias gpu="git push"
alias gpuf="git push -f"
alias gs="git status"
alias master="git checkout master"
alias gll='git log --graph --pretty=oneline --abbrev-commit'
alias gg="git log --graph --pretty=format:'%C(bold)%h%Creset%C(magenta)%d%Creset %s %C(yellow)<%an> %C(cyan)(%cr)%Creset' --abbrev-commit --date=relative"
# From http://blogs.atlassian.com/2014/10/advanced-git-aliases/
# Show commits since last pull
alias gnew="git log HEAD@{1}..HEAD@{0}"
# Add uncommitted and unstaged changes to the last commit
alias gcaa="git commit -a --amend -C HEAD"
alias ggui="git gui"
alias ggs="gg --stat"

## Python Aliases
alias mng="./manage.py"

## Volantio Aliases
alias ctl='./appctl'
alias vol="cd ~/Volantio"
alias vbast="vault ssh -mode otp -role bastion_otp bastion@bastion.volantio.com"
alias vfull="./appctl stop-all && ./appctl start"
alias vres="./appctl restart"
alias vshell="./appctl manage shell"
alias vtest="./appctl server-test --parallel 4"
alias vvault="ll ~ | grep .vault-token" # tells you when your token was last renewed

###############
#  TODOs
######
# Workarounds to support XDG
# - Prezto

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# fzf + ag configuration
if hash fzf && hash ag 2>/dev/null; then
  export FZF_DEFAULT_COMMAND='ag --nocolor -g ""'
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
  export FZF_ALT_C_COMMAND="$FZF_DEFAULT_COMMAND"
  export FZF_DEFAULT_OPTS='
  --color fg:#B7C5D3,bg:#1D252C,hl:#539AFC,fg+:#718CA1,bg+:#333F4A,hl+:#5EC4FF
  --color info:#8BD49C,prompt:#33CED8,spinner:#EBBF83,pointer:#E27E8D,marker:#70E1E8
  '
fi

